<!-- Start EdTech plugin includes -->
	<!-- TODO: to fix validationation errors, see this site http://coolestguidesontheplanet.com/add-javascript-css-files-head-wordpress/ -->
	<!-- Add jQuery library -->
	<script type="text/javascript" src="<?php echo LIBRARIES_URL; ?>/jquery-1.10.1.min.js"></script> 

	<!-- Add fancyBox main JS and CSS files -->
	<script type="text/javascript" src="<?php echo LIGHTBOX_LIB_URL; ?>/source/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" property="stylesheet" type="text/css" href="<?php echo LIGHTBOX_LIB_URL; ?>/source/jquery.fancybox.css?v=2.1.5" />

	<!-- Add EdTech Journals client code/css -->
	<script type="text/javascript" src="<?php echo TABLES_URL; ?>/edtech-journals-table.js"></script>
	<link rel="stylesheet" property="stylesheet" type="text/css" href="<?php echo TABLES_URL; ?>/edtech-journals-table.css" />

	<script type="text/javascript" src="<?php echo LIGHTBOX_URL; ?>/edtech-journals-lightbox.js"></script>
	<link rel="stylesheet" property="stylesheet" type="text/css" href="<?php echo LIGHTBOX_URL; ?>/edtech-journals-lighbox.css" />
<!-- End plugin includes -->